-- =============================================================================
-- Amostra etapa 1: B71 → origem → B53 → AC9 → ACB
-- Substituir:
--   _EMP  = sufixo físico da empresa (ex.: 010 → B71010, BEA010, ...)
--   @DATMOV = data YYYYMMDD a validar (ex.: '20260925')
--   @ULTREC = valor atual de Z_NOTIENCA (ex.: 0)
-- =============================================================================

-- 0) Sanity: B71 do dia no departamento 012
SELECT
    B71.R_E_C_N_O_,
    B71.B71_ALIMOV,
    B71.B71_RECMOV,
    B71.B71_SEQUEN,
    B71.B71_DATMOV,
    B71.B71_CODDEP,
    B71.B71_OPERAD,
    B71.B71_SEGMEN
FROM B71_EMP B71
WHERE B71.D_E_L_E_T_ = ' '
  AND B71.B71_CODDEP = '012'
  AND B71.B71_DATMOV = '@DATMOV'
  AND B71.R_E_C_N_O_ > @ULTREC
ORDER BY B71.R_E_C_N_O_;

-- 1) Contagem por alias de origem
SELECT B71.B71_ALIMOV, COUNT(*) AS QTD
FROM B71_EMP B71
WHERE B71.D_E_L_E_T_ = ' '
  AND B71.B71_CODDEP = '012'
  AND B71.B71_DATMOV = '@DATMOV'
  AND B71.R_E_C_N_O_ > @ULTREC
GROUP BY B71.B71_ALIMOV
ORDER BY QTD DESC;

-- 2) UNION ALL — mesmo shape do fConsulta() (ajuste Left/AllTrim se a amostra exigir)
-- Result set mínimo: R_E_C_N_O_, B71_ALIMOV, B71_RECMOV, B53_NUMGUI, ACB_CODOBJ, ACB_OBJETO

-- BEA (GUIORI)
SELECT
    B71.R_E_C_N_O_ AS B71_RECNO,
    B71.B71_ALIMOV,
    B71.B71_RECMOV,
    B53.B53_NUMGUI,
    ACB.ACB_CODOBJ,
    ACB.ACB_OBJETO
FROM B71_EMP B71
INNER JOIN BEA_EMP BEA
    ON BEA.R_E_C_N_O_ = CAST(B71.B71_RECMOV AS INT)
   AND BEA.D_E_L_E_T_ = ' '
INNER JOIN B53_EMP B53
    ON B53.B53_NUMGUI = LEFT(LTRIM(RTRIM(BEA.BEA_GUIORI)), 18)
   AND B53.D_E_L_E_T_ = ' '
INNER JOIN AC9_EMP AC9
    ON AC9.AC9_CODENT LIKE '%' + LTRIM(RTRIM(B53.B53_NUMGUI)) + '%'
   AND AC9.D_E_L_E_T_ = ' '
INNER JOIN ACB_EMP ACB
    ON ACB.ACB_CODOBJ = AC9.AC9_CODOBJ
   AND ACB.D_E_L_E_T_ = ' '
   AND ACB.ACB_OBJETO <> ' '
WHERE B71.D_E_L_E_T_ = ' '
  AND B71.B71_CODDEP = '012'
  AND B71.B71_DATMOV = '@DATMOV'
  AND B71.R_E_C_N_O_ > @ULTREC
  AND B71.B71_ALIMOV = 'BEA'

UNION ALL

-- BE4 (GUIORI)
SELECT
    B71.R_E_C_N_O_,
    B71.B71_ALIMOV,
    B71.B71_RECMOV,
    B53.B53_NUMGUI,
    ACB.ACB_CODOBJ,
    ACB.ACB_OBJETO
FROM B71_EMP B71
INNER JOIN BE4_EMP BE4
    ON BE4.R_E_C_N_O_ = CAST(B71.B71_RECMOV AS INT)
   AND BE4.D_E_L_E_T_ = ' '
INNER JOIN B53_EMP B53
    ON B53.B53_NUMGUI = LEFT(LTRIM(RTRIM(BE4.BE4_GUIORI)), 18)
   AND B53.D_E_L_E_T_ = ' '
INNER JOIN AC9_EMP AC9
    ON AC9.AC9_CODENT LIKE '%' + LTRIM(RTRIM(B53.B53_NUMGUI)) + '%'
   AND AC9.D_E_L_E_T_ = ' '
INNER JOIN ACB_EMP ACB
    ON ACB.ACB_CODOBJ = AC9.AC9_CODOBJ
   AND ACB.D_E_L_E_T_ = ' '
   AND ACB.ACB_OBJETO <> ' '
WHERE B71.D_E_L_E_T_ = ' '
  AND B71.B71_CODDEP = '012'
  AND B71.B71_DATMOV = '@DATMOV'
  AND B71.R_E_C_N_O_ > @ULTREC
  AND B71.B71_ALIMOV = 'BE4'

UNION ALL

-- B44 (GUIORI)
SELECT
    B71.R_E_C_N_O_,
    B71.B71_ALIMOV,
    B71.B71_RECMOV,
    B53.B53_NUMGUI,
    ACB.ACB_CODOBJ,
    ACB.ACB_OBJETO
FROM B71_EMP B71
INNER JOIN B44_EMP B44
    ON B44.R_E_C_N_O_ = CAST(B71.B71_RECMOV AS INT)
   AND B44.D_E_L_E_T_ = ' '
INNER JOIN B53_EMP B53
    ON B53.B53_NUMGUI = LEFT(LTRIM(RTRIM(B44.B44_GUIORI)), 18)
   AND B53.D_E_L_E_T_ = ' '
INNER JOIN AC9_EMP AC9
    ON AC9.AC9_CODENT LIKE '%' + LTRIM(RTRIM(B53.B53_NUMGUI)) + '%'
   AND AC9.D_E_L_E_T_ = ' '
INNER JOIN ACB_EMP ACB
    ON ACB.ACB_CODOBJ = AC9.AC9_CODOBJ
   AND ACB.D_E_L_E_T_ = ' '
   AND ACB.ACB_OBJETO <> ' '
WHERE B71.D_E_L_E_T_ = ' '
  AND B71.B71_CODDEP = '012'
  AND B71.B71_DATMOV = '@DATMOV'
  AND B71.R_E_C_N_O_ > @ULTREC
  AND B71.B71_ALIMOV = 'B44'

UNION ALL

-- B4Q (GUIREF)
SELECT
    B71.R_E_C_N_O_,
    B71.B71_ALIMOV,
    B71.B71_RECMOV,
    B53.B53_NUMGUI,
    ACB.ACB_CODOBJ,
    ACB.ACB_OBJETO
FROM B71_EMP B71
INNER JOIN B4Q_EMP B4Q
    ON B4Q.R_E_C_N_O_ = CAST(B71.B71_RECMOV AS INT)
   AND B4Q.D_E_L_E_T_ = ' '
INNER JOIN B53_EMP B53
    ON B53.B53_NUMGUI = LTRIM(RTRIM(B4Q.B4Q_GUIREF))
   AND B53.D_E_L_E_T_ = ' '
INNER JOIN AC9_EMP AC9
    ON AC9.AC9_CODENT LIKE '%' + LTRIM(RTRIM(B53.B53_NUMGUI)) + '%'
   AND AC9.D_E_L_E_T_ = ' '
INNER JOIN ACB_EMP ACB
    ON ACB.ACB_CODOBJ = AC9.AC9_CODOBJ
   AND ACB.D_E_L_E_T_ = ' '
   AND ACB.ACB_OBJETO <> ' '
WHERE B71.D_E_L_E_T_ = ' '
  AND B71.B71_CODDEP = '012'
  AND B71.B71_DATMOV = '@DATMOV'
  AND B71.R_E_C_N_O_ > @ULTREC
  AND B71.B71_ALIMOV = 'B4Q'

UNION ALL

-- B4A (GUIREF)
SELECT
    B71.R_E_C_N_O_,
    B71.B71_ALIMOV,
    B71.B71_RECMOV,
    B53.B53_NUMGUI,
    ACB.ACB_CODOBJ,
    ACB.ACB_OBJETO
FROM B71_EMP B71
INNER JOIN B4A_EMP B4A
    ON B4A.R_E_C_N_O_ = CAST(B71.B71_RECMOV AS INT)
   AND B4A.D_E_L_E_T_ = ' '
INNER JOIN B53_EMP B53
    ON B53.B53_NUMGUI = LTRIM(RTRIM(B4A.B4A_GUIREF))
   AND B53.D_E_L_E_T_ = ' '
INNER JOIN AC9_EMP AC9
    ON AC9.AC9_CODENT LIKE '%' + LTRIM(RTRIM(B53.B53_NUMGUI)) + '%'
   AND AC9.D_E_L_E_T_ = ' '
INNER JOIN ACB_EMP ACB
    ON ACB.ACB_CODOBJ = AC9.AC9_CODOBJ
   AND ACB.D_E_L_E_T_ = ' '
   AND ACB.ACB_OBJETO <> ' '
WHERE B71.D_E_L_E_T_ = ' '
  AND B71.B71_CODDEP = '012'
  AND B71.B71_DATMOV = '@DATMOV'
  AND B71.R_E_C_N_O_ > @ULTREC
  AND B71.B71_ALIMOV = 'B4A'

ORDER BY 1;

-- 3) Diagnóstico se o UNION vier vazio: B71 + origem + guia, sem AC9/ACB
-- (descomente e ajuste o alias; exemplo BEA)
/*
SELECT
    B71.R_E_C_N_O_,
    B71.B71_ALIMOV,
    B71.B71_RECMOV,
    LTRIM(RTRIM(BEA.BEA_GUIORI)) AS GUIORI,
    B53.B53_NUMGUI
FROM B71_EMP B71
INNER JOIN BEA_EMP BEA
    ON BEA.R_E_C_N_O_ = CAST(B71.B71_RECMOV AS INT)
   AND BEA.D_E_L_E_T_ = ' '
LEFT JOIN B53_EMP B53
    ON B53.B53_NUMGUI = LEFT(LTRIM(RTRIM(BEA.BEA_GUIORI)), 18)
   AND B53.D_E_L_E_T_ = ' '
WHERE B71.D_E_L_E_T_ = ' '
  AND B71.B71_CODDEP = '012'
  AND B71.B71_DATMOV = '@DATMOV'
  AND B71.B71_ALIMOV = 'BEA';
*/

-- Nota Oracle/Postgres: trocar CAST(... AS INT), LTRIM/RTRIM/LEFT pela sintaxe do SGBD.
-- No TLPP o job usará RetSqlName + Val(B71_RECMOV) + AllTrim.
